### PR TITLE
Add limit for maximum diameter circular buildings (relevant for ADMS)

### PR DESCRIPTION
**Pull request by Hilbrand**

### CODE REVIEW

**Review by BertScholten — APPROVED** [review]
LGTM

**Comment by Hilbrand** [comment]
Yes it would be good to add this to the `BuildingValidator`. There are some other building limits. It's probably good to also add them to the validator.

**Comment by BertScholten** [comment]
Added something along those lines to https://github.com/aerius/IMAER-java/pull/283 (was an unassigned issue for this, and I had forgotten this PR... apparantly a week is enough time to forget)

**Comment by Hilbrand** [comment]
Closing because superseded by #283

**Pull request closed without merging**
